Default Commit

diff --git a/scripts/common/mynslookup b/scripts/common/mynslookup
--- a/scripts/common/mynslookup
+++ b/scripts/common/mynslookup
@@ -1,21 +1,16 @@
 #!/bin/bash
 
-#!/bin/bash
-
 if [ -n "$1" ]; then
-    input="$1"
-
-    [ ! -f "$input" ] && { echo "Input file not found: $input"; exit 1; }
-else
-    [ -t 0 ] && { echo "No input file provided and nothing piped to stdin"; exit 1; }
-
-    input="/dev/stdin"
+    [ ! -f "$1" ] && { echo "Input file not found: $1"; exit 1; }
+    exec < "$1"
+elif [ -t 0 ]; then
+    echo "No input file provided or piped"
+    exit 1
 fi
 
 while read -r fqdn
 do
-    fqdn_ip=$(nslookup "$fqdn" | grep Address: | grep -v \# | tail -1 | awk '{print $NF}')
+    fqdn_ip=$(nslookup "$fqdn" | grep 'Address:' | grep -v '#' | tail -1 | awk '{print $NF}')
     echo "$fqdn $fqdn_ip"
-done < "$input"
-
+done
 
